spring.application.name=cge-agenda
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_agenda
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

